############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Privacy"
url = "privacy-policy/"
weight = 2

[[footer]]
name = "Impressum"
url = "impressum/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4
