############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1
#
# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 2
#

# footer menu
[[footer]]
name = "Impressum"
url = "impressum/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 4
